cartridge_accounting/cartridge_accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

cartridge_accounting/cartridges/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import CartridgeDeleteView

app_name = 'cartridges'




urlpatterns = [
    path('', views.CartridgeListView.as_view(), name='cartridges_list',),
    path('search/', views.Search.as_view(), name='search'),
    path('<int:pk>/update/', views.CartridgeUpdateView.as_view(), name='cartridges_update'),
    path('delete/<int:pk>/', CartridgeDeleteView.as_view(), name='cartridge_delete'),
    path('cartridge_manage/', views.CartridgeManageView.as_view(), name='cartridge_manage'),
    path('cartridge/<int:pk>/commission/', views.commission, name='commission'),
    path('commissioned/', views.commissioned_list, name='commissioned_list'),
] + static (settings.STATIC_URL, document_root = settings.STATIC_ROOT)

cartridge_accounting/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('cartridges.urls', namespace='cartridges')),
]

cartridge_accounting/cartridges/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from datetime import date

User = get_user_model()




User = get_user_model()

class Cartridge(models.Model):
    name = models.CharField(
        verbose_name='Наименование картриджа',
        max_length=50
    )
    device_name = models.CharField(
        verbose_name='Наименование устройства',
        max_length = 50
    )
    acceptance_date = models.DateField(
        verbose_name='Дата получения',
    )
    decommissioning_date = models.DateField(
        verbose_name='Дата ввода в эксп.',
        null=True
    )
    inventory_number = models.IntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='инвентарный номер',
        unique=True,
    )
    is_functional = models.BooleanField(
        default=True,
        verbose_name='рабочий',
        null=True
    )
    added_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Добавил'
    )


    class Meta:
        ordering = ('acceptance_date',)
        verbose_name = 'картридж'
        verbose_name_plural = 'картриджи'

    def __str__(self):
        return f'Картридж для устройства {self.device_name}'

class CartridgeCommissioning(models.Model):
    cartridge = models.OneToOneField(
        'Cartridge',
        on_delete=models.CASCADE,
        verbose_name='Картридж'
    )
    location = models.CharField(
        verbose_name='Место установки',
        max_length=100
    )
    date = models.DateField(
        verbose_name='Дата ввода',
        auto_now_add=True
    )
    expl_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Ввел в эксплуатацию'
    )
class CommissionedCartridge(models.Model):
    name = models.CharField(
        verbose_name='Наименование картриджа',
        max_length=50,
        default='Не указано'  # Добавляем
    )
    device_name = models.CharField(
        verbose_name='Наименование устройства',
        max_length=50,
        default='Не указано'  # Добавляем
    )
    acceptance_date = models.DateField(
        verbose_name='Дата получения',
        default=date.today  # Добавляем
    )
    decommissioning_date = models.DateField(
        verbose_name='Дата ввода в эксп.',
        default=date.today  # Добавляем
    )
    inventory_number = models.IntegerField(
        verbose_name='инвентарный номер',
        default=0  # Добавляем
    )
    is_functional = models.BooleanField(
        verbose_name='рабочий',
        default=True  # Добавляем
    )
    location = models.CharField(
        verbose_name='Место установки',
        max_length=100,
        default='Не указано'  # Добавляем
    )
    commission_date = models.DateField(
        verbose_name='Дата ввода',
        auto_now_add=True
    )
    expl_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Ввел в эксплуатацию'
    )

    class Meta:
        verbose_name = 'Введённый в эксплуатацию картридж'
        verbose_name_plural = 'Введённые в эксплуатацию картриджи'

cartridge_accounting/cartridges/forms.py
from django import forms
from .models import Cartridge
from .models import CartridgeCommissioning

class CartridgeCreateForm(forms.ModelForm):
    class Meta:
        model = Cartridge
        fields = [
            'name',
            'device_name',
            'acceptance_date',
            'inventory_number',
            'added_by',
        ]
        widgets = {
            'acceptance_date': forms.DateInput(
                attrs={'type': 'date'}
            ),
        }
class CartridgeUpdateForm(forms.ModelForm):
    class Meta(CartridgeCreateForm.Meta):
        fields = [
            'name',
            'device_name',
            'acceptance_date',
            'inventory_number',
        ]
class CommissioningForm(forms.ModelForm):
    class Meta:
        model = CartridgeCommissioning
        fields = ['location']

cartridge_accounting/cartridges/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.views.generic import ListView, UpdateView, DeleteView
from .forms import CartridgeCreateForm,CartridgeUpdateForm
from .models import Cartridge, CommissionedCartridge
from datetime import date

class CartridgeListView(ListView):
    model = Cartridge
    template_name = 'cartridges/main.html'
    context_object_name = 'cartridges'

    def get_queryset(self):
        return Cartridge.objects.only(
            'name', 'device_name', 'acceptance_date', 'inventory_number'
        )


# class CartridgeManageView(View):
#     template_name = 'cartridge_form.html'
#
#     def get(self, request, pk=None):
#         if pk:
#             obj = get_object_or_404(Cartridge, pk=pk)
#             form = CartridgeCreateForm(instance=obj)
#         else:
#             form = CartridgeCreateForm()
#         cartridges = Cartridge.objects.all()
#         return render(request, self.template_name, {
#             'form': form,
#             'cartridges': cartridges,
#             'pk': pk,
#         })
#
#     def post(self, request, pk=None):
#         if 'delete' in request.POST:
#             obj = get_object_or_404(Cartridge, pk=pk)
#             obj.delete()
#             return redirect('cartridge_manage')
#         else:
#             if pk:
#                 obj = get_object_or_404(Cartridge, pk=pk)
#                 form = CartridgeCreateForm(request.POST, instance=obj)
#             else:
#                 form = CartridgeCreateForm(request.POST)
#             if form.is_valid():
#                 form.save()
#                 return redirect('cartridge_manage')
#         cartridges = Cartridge.objects.all()
#         return render(request, self.template_name, {
#             'form': form,
#             'cartridges': cartridges,
#             'pk': pk,
#         })

class CartridgeManageView(View):
    template_name = 'cartridges/cartridge_form.html'

    def get(self, request):
        form = CartridgeCreateForm()
        cartridges = Cartridge.objects.all()
        return render(request, self.template_name, {
            'form': form,
            'cartridges': cartridges,
        })

    def post(self, request):
        form = CartridgeCreateForm(request.POST)
        if form.is_valid():
            cartridge = form.save(commit=False)
            cartridge.added_by = request.user
            cartridge.save()
            return redirect('/')
        cartridges = Cartridge.objects.all()
        return render(request, self.template_name, {
            'form': form,
            'cartridges': cartridges,

        })

class CartridgeUpdateView(UpdateView):
    model = Cartridge
    form_class = CartridgeUpdateForm
    template_name = 'cartridges/cartridge_update.html'
    success_url = '/'
class CartridgeDeleteView(DeleteView):
    model = Cartridge
    success_url = '/'


def commission(request, pk):
    cartridge = get_object_or_404(Cartridge, pk=pk)

    if request.method == 'POST':
        location = request.POST.get('location', '').strip()
        cartridge.expl_by = request.user

        if location:
            CommissionedCartridge.objects.create(
                name=cartridge.name,
                device_name=cartridge.device_name,
                acceptance_date=cartridge.acceptance_date,
                decommissioning_date=cartridge.decommissioning_date or date.today(),
                inventory_number=cartridge.inventory_number,
                is_functional=cartridge.is_functional,
                location=location,
                expl_by= request.user
            )

            cartridge.delete()

            return redirect('cartridges:commissioned_list')

    return render(request, 'cartridges/commission.html', {'cartridge': cartridge})


def commissioned_list(request):
    commissioned_cartridges = CommissionedCartridge.objects.all().order_by('-decommissioning_date')
    return render(request, 'cartridges/commissioned_list.html', {
        'commissioned_cartridges': commissioned_cartridges
    })


class Search(ListView):
    model = Cartridge
    template_name = 'cartridges/main.html'
    context_object_name = 'cartridges'

    def get_queryset(self):
        name_query = self.request.GET.get('name', '')
        device_query = self.request.GET.get('device', '')
        date_from = self.request.GET.get('date_from')
        date_to = self.request.GET.get('date_to')
        inv_number_query = self.request.GET.get('inventory_number','')
        user_query = self.request.GET.get('added_by', '')
        user_id = self.request.GET.get('user')

        queryset = Cartridge.objects.all()

        if name_query:
            queryset = queryset.filter(name__icontains=name_query)
        if device_query:
            queryset = queryset.filter(device_name__icontains=device_query)
        if date_from:
            queryset = queryset.filter(acceptance_date__gte=date_from)
        if date_to:
            queryset = queryset.filter(acceptance_date__lte=date_to)
        if inv_number_query:
            queryset = queryset.filter(inventory_number__icontains=inv_number_query)
        if user_query:
            queryset = queryset.filter(added_by__icontains=inv_number_query)
        if user_id:
            queryset = queryset.filter(added_by_id=user_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        User = get_user_model()
        context['name_query'] = self.request.GET.get('name', '')
        context['device_query'] = self.request.GET.get('device', '')
        context['users'] = User.objects.all()
        context['selected_user'] = self.request.GET.get('user', '')
        return context

cartridge_accounting/cartridges/templates/cartridges/cartridge_form.html
{% extends 'cartridges/layout.html' %}
{% load static %}

{% block title %} Редактор картриджей{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'cartridges/css/cartridges.css' %}">
{% endblock %}

{% block content %}
<h1>
    {% if pk %}
        Редактировать картридж: {{ form.instance }}
    {% else %}
        Добавить картридж
    {% endif %}
</h1>

<form method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <div class="errorlist">{{ form.non_field_errors }}</div>
    {% endif %}
    <table>
        {% for field in form %}
            <tr>
                <td><strong>{{ field.label_tag }}</strong></td>
                <td>
                    {{ field }}
                    {% if field.errors %}
                        <div class="errorlist">{{ field.errors|striptags }}</div>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <button type="submit">Сохранить</button>
    {% if pk %}
        <button type="submit" name="delete" class="delete-btn" onclick="return confirm('Удалить этот картридж?');">
            Удалить
        </button>
    {% endif %}
</form>

<hr>

<div class="cartridge-list">
    <h2>Все картриджи</h2>
    <ul>
        {% for cartridge in cartridges %}
            <li>
                {{ cartridge.name }}
                [<a href="{% url 'cartridges:cartridges_update' cartridge.pk %}">Изменить/Удалить</a>]
            </li>
        {% empty %}
            <li>Нет картриджей</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

cartridge_accounting/cartridges/templates/cartridges/cartridge_update.html
{% extends 'cartridges/layout.html' %}
{% load static %}



{% block title %}Обновление картриджа {% endblock %}
{% block content %}
    <h1>Обновление информации о картридже</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить изменения</button>
    </form>
{% endblock %}

cartridge_accounting/cartridges/templates/cartridges/commission.html
<form method="post">
    {% csrf_token %}
    <h4>Ввод картриджа в эксплуатацию:</h4>
    <p><strong>Наименование:</strong> {{ cartridge.name }}</p>
    <p><strong>Устройство:</strong> {{ cartridge.device_name }}</p>
    <p><strong>Инвентарный номер:</strong> {{ cartridge.inventory_number }}</p>

    <div class="form-group">
        <label for="location">Место установки:</label>
        <input type="text" id="location" name="location" class="form-control" required>
    </div>
        <div class="form-group">
        <label for="expl_by">Ввел в эксплуатацию:</label>
        <select id="expl_by" name="expl_by" class="form-control" required>
            <option value="{{ user.id }}">
                    {{ user.get_full_name|default:user.username }}
                </option>
        </select>
    </div>


    <button type="submit" class="btn btn-primary">Подтвердить ввод в эксплуатацию</button>
</form>

cartridge_accounting/cartridges/templates/cartridges/commissioned_list.html
{% extends 'cartridges/layout.html' %}
{% load static %}

{% block title %}Введённые в эксплуатацию картриджи{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'cartridges/css/cartridges_list.css' %}">
{% endblock %}

{% block content %}
    <div class="head-row">
        <h1>Введённые в эксплуатацию картриджи</h1>
    </div>
    <table>
        <thead>
            <tr>
                <th>Наименование картриджа</th>
                <th>Наименование устройства</th>
                <th>Дата получения</th>
                <th>Дата ввода в эксп.</th>
                <th>Инвентарный номер</th>
                <th>Место установки</th>
                <th>Ввел в эксплуатацию</th>

            </tr>
        </thead>
        <tbody>
            {% for item in commissioned_cartridges %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.device_name }}</td>
                    <td>{{ item.acceptance_date|date:"d.m.Y" }}</td>
                    <td>{{ item.decommissioning_date|date:"d.m.Y" }}</td>
                    <td>{{ item.inventory_number }}</td>
                    <td>{{ item.location }}</td>
                    <td>{{ item.expl_by }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="7">Нет данных</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

cartridge_accounting/cartridges/templates/cartridges/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <!--    Блок для подключения css  -->
    {% block link %} {% endblock %}
    <!--   -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/cartridges/css/navbar.css">
</head>
<body>
{% if request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'cartridges:cartridges_list' %}">Список картриджей</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'cartridges:commissioned_list' %}">Введённые в эксплуатацию</a>
    </li>
  </ul>
  <ul class="navbar-nav ms-auto">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}" class="logout-button">Выйти</a>
    </li>
  </ul>
</div>
</nav>
    {% block content %}
    {% endblock %}
{% else %}
<a href='/auth/login'>Авторизация </a>
{% endif %}
</body>
</html>

cartridge_accounting/cartridges/templates/cartridges/main.html
{% extends 'cartridges/layout.html' %}
{% load static %}

{% block title %} Список картриджей{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'cartridges/css/cartridges_list.css' %}">
{% endblock %}

<!--body-->
{% block content %}
<!--    <div class="top-bar">-->
<!--        <a href="{% url 'logout' %}" class="logout-button">Выйти</a>-->
<!--    </div>-->
    <div class="head-row">
        <h1>Список картриджей</h1>
        <a href="{% url 'cartridges:cartridge_manage' %}" class="add-button">Добавить картридж</a>
    </div>
    <table>
        <thead>
            <tr>
                <th>Наименование картриджа</th>
                <th>Наименование устройства</th>
                <th>Дата получения</th>
                <th>Инвентарный номер</th>
                <th>Добавил</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <td><form action="{% url 'cartridges:search' %}"method="get"><input type='search'type="text"name="name"placeholder="наименованию"value="{{ name_query|default:'' }}"> <button type="submit"> Найти</button></form></td>
            <td><form action="{% url 'cartridges:search' %}"method="get"><input type='search'type="text"name="device"placeholder="наименованию"value="{{ device_query|default:'' }}"> <button type="submit"> Найти</button></form></td>
            <td><form method="get" action="{% url 'cartridges:search' %}"><input type="date" name="date_from"> до<input type="date" name="date_to"><button type="submit">Найти</button></form></td>
            <td><form action="{% url 'cartridges:search' %}"method="get"><input type='search'type="text"name="inventory_number"placeholder="Инвентарный"value="{{ inv_number_query|default:'' }}"> <button type="submit"> Найти</button></form></td>
            <td>
                <form method="get" action="{% url 'cartridges:search' %}">
                    <select name="user">
                        <option value="">Все пользователи</option>
                        {% for user in users %}
                        <option value="{{ user.id }}"
                                {% if selected_user == user.id|stringformat:"s" %}selected{% endif %}>
                            {{ user.username }}
                        </option>
                        {% endfor %}
                    </select>
                    <button type="submit">Фильтровать</button>
                </form>
            </td>

            {% for cartridge in cartridges %}
                <tr>
                    <td>{{ cartridge.name }}</td>
                    <td>{{ cartridge.device_name }}</td>
                    <td>{{ cartridge.acceptance_date|date:"d.m.Y" }}</td>
                    <td>{{ cartridge.inventory_number }}</td>
                    <td>{{ cartridge.added_by }}</td>
                    <td><a href="{% url 'cartridges:cartridges_update' cartridge.pk %}" class="button-like">Изменить</a></td>
                    <td><a href="{% url 'cartridges:commission' cartridge.id %}" class="btn btn-success">Ввести в эксплуатацию</a></td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">Нет данных</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}